name: Grasshopper
favicon: null
layout_spectrum: 0.9029027752112597
typography_spectrum: 0.009084317600354552
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff2603'
    - '#000000'
    - '#c7c7c7'
    - '#5f5f5f'
  brandStrength: 0.375
  lightness: 0.8401045964565128
  saturation: 0.3726075382437557
  rhythmicContrast: 0.6080524262506515
purpose: []
