typography_spectrum: 0.221
color:
  brandColors:
    - '#ffffff'
    - '#ff2603'
    - '#000000'
    - '#c7c7c7'
    - '#5f5f5f'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.70537
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a23f6d35-46a5-476f-92d8-49485fed14f1.png
name: Grasshopper
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Grasshopper Enterprises, LLC'
purpose: []
