name: Grasshopper
favicon: null
layout_spectrum: 0.70537
typography_spectrum: 0.221
title: 'Grasshopper Enterprises, LLC'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff2603'
    - '#000000'
    - '#c7c7c7'
    - '#5f5f5f'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
